apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: krebiehl-tsig-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv

  target:
    name: edns-secret-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          rfc2136:
            tsigSecret: "{{ .tsigSecret | toString }}"

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: tsigSecret
      remoteRef:
        key: krebiehl-dns-tsig-secret
