apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: krebiehl-tsig-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv

  target:
    name: krebiehl-dns-tsig
    creationPolicy: Owner
    template:
      data:
        rfc2136.tsigSecret: "{{ .tsig | toString }}"

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: tsig
      remoteRef:
        key: krebiehl-dns-tsig-secret
