apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: krebiehl-ca
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akv

  target:
    name: krebiehl-ca
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt | pemCertificate }}"
        tls.key: "{{ .key | pemPrivateKey }}"

  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: crt
      remoteRef:
        key: krebiehl-ca-pem
    - secretKey: key
      remoteRef:
        key: krebiehl-ca-key
